### ISSUE TITLE
Problem running yamltodb - throws AttributeError processing yaml

### ISSUE THREAD

**Issue by montgomeryb** [perseas/Pyrseas#159] opened 2017-03-21 03:04 UTC
Hi,
So I have two servers, both running 9.6.1. I tried against the main dev db, and was able to produce a file with dbtoyaml.
However, I received an exception when trying to use yamltodb. I then tried it with just the postgres database and it produced a very similar error.
I have attached the p.yaml file renamed to p.txt and a capture of the console output.
I will say that I am pretty new to python. I also had infrastructure issues getting pip to work, but it did seem to install yaml and Pyrseas. However, maybe there is a bigger error than something with Pyrseas?

[output.txt](https://github.com/perseas/Pyrseas/files/857007/output.txt)
[p.txt](https://github.com/perseas/Pyrseas/files/857009/p.txt)

**Comment by jmafc** [comment] 2017-03-21 04:32
First, please advise the Pyrseas version (`dbtoyaml --version`).

Second, the first error (the one that says "'str' object has no attribute 'capital'" is something we'll have to fix. If you want you can edit the file `pyrseas/dbobject/table.py` under your `site-packages` folder and at line 776 replace `capital()` by `capitalize()`.

After you fix that, you'll still get another error similar to the second one, because if you look at the code around that `capital()` you'll see it was trying to tell you that some object "has privileges but no owner information".

The problem is you ran both `dbtoyaml` invocations with `--no-owner`. I'll have to check the documentation later, but if you create a YAML file with no owner information but with some privileges referring to users (other than `postgres` probably), `yamltodb` can't understand/resolve the privileges, so your options are to use both `--no-owner` and `--no-privileges` (`-Ox`), don't include either or only use `--no-privileges). We should probably try to enforce these rules, if possible.

**Comment by montgomeryb** [comment] 2017-03-21 10:38
Thank you for the prompt response! The version I have is 0.7.3

After changing table.py and re-running without the --no-owner, I was able to run it to completion :)

I also ran it with the no-owner and no-privilegs, and it also ran to completion.

**Comment by jmafc** [comment] 2017-03-27 21:07
AFAICT this problem has been addressed in the current development version (0.8.dev0), because of the changes made to add name, description, owner and privileges attributes to *all* `DbObject`s (see change 5da6b0c). Therefore, no further action is necessary.

**Closed by jmafc** 2017-03-27 21:07 UTC
Labels: yamltodb
