### ISSUE TITLE
yamltodb fails on alter column set statistics

### ISSUE THREAD

**Issue by darthunix** [perseas/Pyrseas#140] opened 2016-07-27 11:54 UTC
It seems that Pyrseas from r0.7 branch currently doesn't support [set statistics](https://www.postgresql.org/docs/9.5/static/sql-altertable.html) statment in "alter table ... alter column..." sql command.
Steps to reproduce:

- Create new database (`createdb testdb`)

- Create a table in testdb
```
create table test (id integer) with (oids=false);
alter table test alter column id set statistics 0;
```

- Run dbtoyaml  (`dbtoyaml testdb > [testdb_yaml.txt](https://github.com/perseas/Pyrseas/files/385942/testdb_yaml.txt)')

- Compare testdb_yaml.txt with original testdb via yamltodb
`yamltodb testdb testdb_yaml.txt`

At this moment we get errors:
```
Traceback (most recent call last):
  File "/home/darthunix/venv/pyrseas/bin/yamltodb", line 9, in <module>
    load_entry_point('Pyrseas==0.7.2', 'console_scripts', 'yamltodb')()
  File "/home/darthunix/venv/pyrseas/lib/python3.5/site-packages/Pyrseas-0.7.2-py3.5.egg/pyrseas/yamltodb.py", line 45, in main
    stmts = db.diff_map(inmap)
  File "/home/darthunix/venv/pyrseas/lib/python3.5/site-packages/Pyrseas-0.7.2-py3.5.egg/pyrseas/database.py", line 360, in diff_map
    stmts.append(self.db.tables.diff_map(self.ndb.tables))
  File "/home/darthunix/venv/pyrseas/lib/python3.5/site-packages/Pyrseas-0.7.2-py3.5.egg/pyrseas/dbobject/table.py", line 959, in diff_map
    stmts.append(table.diff_map(intables[(sch, tbl)]))
  File "/home/darthunix/venv/pyrseas/lib/python3.5/site-packages/Pyrseas-0.7.2-py3.5.egg/pyrseas/dbobject/table.py", line 412, in diff_map
    (stmt, descr) = self.columns[num].diff_map(incol)
  File "/home/darthunix/venv/pyrseas/lib/python3.5/site-packages/Pyrseas-0.7.2-py3.5.egg/pyrseas/dbobject/column.py", line 171, in diff_map
    if self.statistics == -1 and (hasattr(incol, 'statistics') and
AttributeError: 'Column' object has no attribute 'statistics'
```

**Comment by jmafc** [comment] 2016-07-27 13:50
That's strange (again :-) ). We specifically have a test (`tests/dbobject/test_column.py test_alter_statistics`) that checks that (using 100 as the value but that shouldn't matter) and I've just checked that it passes. I'll go through your steps later.

**Comment by jmafc** [comment] 2016-07-27 19:15
Confirmed problem. The weird part is that this behavior has been there since change 2a794ff, i.e., the one where I added support `ALTER COLUMN SET STATISTICS`! Obviously the aforementioned test didn't help much.

**Comment by jmafc** [comment] 2016-07-27 20:42
This was already fixed in master (in a slightly different way) by change f00b74dc, so there is no need to merge there.

**Closed by jmafc** 2016-07-27 20:42 UTC
Labels: yamltodb
